第8回収録
diverse-inc/diverse-podcast pull request #10
Opened 2019-02-14 08:01 UTC by imaizume

音源は別でレビューしていただき、後ほど `audio/8.mp3` に追加します。

2019-02-15 02:50 UTC, kikuchy requested changes
敬称は直していただけると…！

2019-02-15 02:50 UTC, kikuchy commented on _posts/2019-02-08-8.md
> +description: mhidaka（日高）とimaizume（今泉）の二人が、DroidKaigi 2019と技術書典の概要、運営にまつわるやりがいと苦労、技術イベントに対する企業の関わり方、技術イベントを開催するモチベーションについて話しました。
ゲストの方は社員ではないので敬称付けたほうが良いかと！

あと公開収録であることがわかると良いかなと思います。

2019-02-15 02:50 UTC, kikuchy commented on _posts/2019-02-08-8.md
> +title: 8. 大規模技術イベントの運営との付き合い方（DroidKaigiや技術書典の運営裏話と開催にむけての想い）
title 👍

2019-02-19 06:39 UTC, imaizume commented on _posts/2019-02-08-8.md
> +description: mhidaka（日高）とimaizume（今泉）の二人が、DroidKaigi 2019と技術書典の概要、運営にまつわるやりがいと苦労、技術イベントに対する企業の関わり方、技術イベントを開催するモチベーションについて話しました。
@kikuchy そうですね、 #9 の方をコピーさせていただきました。

2019-02-19 06:47 UTC, kikuchy approved these changes
LGTM

2019-02-19 06:49 UTC, merged